name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Install Nodejs
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run compile-tests

      - name: Build extension
        run: npm run compile

      - name: Package extension
        run: npx vsce package

  prerelease-code-marketplace:
    name: 'Pre-release (Code Marketplace)'
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: npm ci

      - name: Publish Extension (Code Marketplace, pre-release)
        run: npx vsce publish --pre-release --pat ${{ secrets.MARKETPLACE_TOKEN }}

  prerelease-openvsx:
    name: 'Pre-release (OpenVSX)'
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: npm ci

      - name: Publish Extension (OpenVSX, pre-release)
        run: npx ovsx publish --pre-release --pat ${{ secrets.OPENVSX_TOKEN }}
        timeout-minutes: 2
