name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run compile-tests

      - name: Build extension
        run: npm run compile

      - name: Package extension
        run: npx vsce package
